services:
  api-auth:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: auth-service
    command: cargo watch -x run
    depends_on:
      - db-auth
      - redis-auth
    volumes:
      - ./:/app
    networks:
      - amaterasu-network

  redis-auth:
    image: "redis:7.0-alpine"
    container_name: auth-service-redis
    ports:
      - "6379:6379"
    networks:
      - amaterasu-network

  db-auth:
    image: postgres:16
    container_name: auth-service-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: auth-service-pass
      POSTGRES_USER: auth-service-user
      POSTGRES_DB: auth-service-db
    volumes:
      - ./storage/db:/var/lib/postgresql/data
    networks:
      - amaterasu-network

  flyway-auth:
    image: flyway/flyway
    container_name: auth-service-migrate
    volumes:
      - ./migrations:/flyway/sql
    command: -url=jdbc:postgresql://db-auth:5432/auth-service-db -schemas=public -user=auth-service-user -password=auth-service-pass -connectRetries=60 -outOfOrder=true migrate
    depends_on:
      - db-auth
    networks:
      - amaterasu-network

networks:
  amaterasu-network:
    name: amaterasu-network
    driver: bridge